runtime: php83

handlers:
- url: /navionics-boating.ms
  script: navionics-boating.ms.php

- url: /navionics-sonar.ms
  script: navionics-sonar.ms.php

- url: /eniro-navionics.ms
  script: eniro-navionics.ms.php

- url: /navionics-boating-tile/\d+/\d+/\d+
  script: navionics-boating-tile.php

- url: /(.+\.ms)$
  static_files: \1
  upload: .+\.ms$
  mime_type: application/x-galileo
  http_headers:
      Content-Disposition: attachment

- url: /(.+\.png)$
  static_files: \1
  upload: .+\.png$

- url: /(.+\.jpg)$
  static_files: \1
  upload: .+\.jpg$

- url: /
  static_files: index.html
  upload: index\.html
