<?xml version="1.0" encoding="UTF-8"?>
<customMapSource>
<name>Lantmäteriets Topografisk</name>
<url>https://api.lantmateriet.se/open/topowebb-ccby/v1/wmts/token/382a0381-7b89-352b-9e8c-26964c1cdf8e/?SERVICE=WMTS&amp;REQUEST=GetTile&amp;VERSION=1.0.0&amp;LAYER=topowebb&amp;STYLE=default&amp;TILEMATRIXSET=3857&amp;TILEMATRIX={$z}&amp;TILEROW={$y}&amp;TILECOL={$x}&amp;FORMAT=image/png</url>
</customMapSource>
