<?xml version="1.0" encoding="UTF-8"?>
<customMapSource>
<name>Lantmäteriets Min karta Flygbild ca 1970-1990</name>
<url>https://minkarta.lantmateriet.se/map/historiskaortofoto/?SERVICE=WMS&amp;VERSION=1.1.1&amp;REQUEST=GetMap&amp;FORMAT=image%2Fpng&amp;TRANSPARENT=false&amp;LAYERS=OI.Histortho_75&amp;TILED=true&amp;STYLES=&amp;WIDTH=256&amp;HEIGHT=256&amp;SRS=EPSG%3A3857&amp;BBOX={$bbox}</url>
</customMapSource>
