<?xml version="1.0" encoding="UTF-8"?>
<customMapSource>
<name>Lantmäteriets Flygbild</name>
<url>https://{$serverpart}SERVICE=WMS&amp;VERSION=1.1.1&amp;REQUEST=GetMap&amp;FORMAT=image%2Fpng&amp;LAYERS=Ortofoto_0.5%2COrtofoto_0.4%2COrtofoto_0.25%2COrtofoto_0.16&amp;WIDTH=256&amp;HEIGHT=256&amp;SRS=EPSG%3A3857&amp;BBOX={$bbox}</url>
<serverParts>minkarta.lantmateriet.se/map/ortofoto/? &#110;&#118;&#100;&#98;&#50;&#48;&#49;&#50;.&#116;&#114;&#97;&#102;&#105;&#107;&#118;&#101;&#114;&#107;&#101;&#116;.se/MapProxy.ashx?mapsvc=GDX&amp; &#114;&#112;&#114;&#111;&#120;&#121;.&#109;&#115;&#98;.se/lantmateriet_ortofoto_v13/? &#109;&#97;&#112;&#115;.&#115;&#103;&#117;.se/lmv/ortofoto/v1.3? &#107;&#97;&#114;&#116;&#97;.&#114;&#97;&#97;.se/lmortofoto?</serverParts>
</customMapSource>
