<?xml version="1.0" encoding="UTF-8"?>
<customMapSource overlay="true">
<name>Lantmäteriets Min karta Fastighetsgränser (ljust lager)</name>
<url>https://minkarta.lantmateriet.se/map/fastighetsindelning/?SERVICE=WMS&amp;VERSION=1.1.1&amp;REQUEST=GetMap&amp;FORMAT=image%2Fpng&amp;TRANSPARENT=true&amp;LAYERS=granser%2Ctext&amp;TILED=true&amp;STYLES=registerkarta%2Cregisterkarta&amp;WIDTH=256&amp;HEIGHT=256&amp;SRS=EPSG%3A3857&amp;BBOX={$bbox}</url>
</customMapSource>
