<?xml version="1.0" encoding="UTF-8"?>
<customMapSource>
<name>Lantmäteriverket Terrängkarta / Maanmittauslaitos Maastokartta</name>
<url>https://avoin-karttakuva.maanmittauslaitos.fi/avoin/wmts?layer=maastokartta&amp;style=default&amp;tilematrixset=WGS84_Pseudo-Mercator&amp;Service=WMTS&amp;Request=GetTile&amp;Version=1.0.0&amp;Format=image%2Fpng&amp;TileMatrix={$z}&amp;TileCol={$x}&amp;TileRow={$y}</url>
</customMapSource>
