<?xml version="1.0" encoding="UTF-8"?>
<customMapSource overlay="true">
<name>Trafikverket NVDB Slitlager (Asfalt/grus)</name>
<tileSize>512</tileSize>
<opacity>0.8</opacity>
<url>https://nvdbpakarta.trafikverket.se/api/MapProxy/mapProxy/NetInfo?REQUEST=GetMap&amp;SERVICE=WMS&amp;VERSION=1.1.1&amp;FORMAT=image%2Fpng&amp;STYLES=&amp;TRANSPARENT=true&amp;LAYERS=Slitlager&amp;WIDTH=512&amp;HEIGHT=512&amp;SRS=EPSG%3A3857&amp;BBOX={$bbox}</url>
</customMapSource>
